consul-client:
  consul-server-ip: 192.168.171.34:8500
  ttl: 10s
  service-name: raspi-temperature-service
  client-address: dummy.hostname.domain
  client-port: 8083
dbconfig:
  type: postgres
  host: 192.168.171.34
  port: 5432
  dbname: pitemp
  username: pitemp
  password: pitemp
  device-id: dev_probook440